### ISSUE TITLE
sudo python3 streaming_setup.py --compile-ffmpeg

### ISSUE THREAD

**Issue by K-a-R-e-N** [cdgriffith/pi_streaming_setup#10]
sudo python3 streaming_setup.py --compile-ffmpeg

Model Info: Raspberry Pi 3 Model B Rev 1.2
Traceback (most recent call last):
  File "streaming_setup.py", line 877, in <module>
    main()
  File "streaming_setup.py", line 856, in main
    extra_libs=" ".join(extra_libs), minimal_install=args.minimal,
  File "streaming_setup.py", line 363, in compile_ffmpeg
    processor_info = raspberry_proc_info()  # Needs to be here to proper error before the apt install
  File "streaming_setup.py", line 235, in raspberry_proc_info
    if "armv7" in results['architecture']:
KeyError: 'architecture'

**Comment by cdgriffith** [comment]
Hi @K-a-R-e-N  this issue should now be resolved in latest 1.5.1 thanks to @rezrov! 

Sorry for delay, I was apparently not watching this repo so I didn't receive notifications ☹️
